install.packages("glmx")
library(glmx)
install.packages("titanic")
library(titanic)
install.packages("tibble")
library(tibble)
as_tibble(titanic::titanic_train)
titanic.glm <- glm(Survived~SibSp+ Fare,family = poisson(),titanic_train)
summary(titanic.glm)
install.packages("ggplot2")
library(ggplot2)
ggplot(titanic.glm, aes(Survived , Fare)) + geom_line()
ggplot(titanic.glm, aes(Survived , SibSp)) + geom_line()

